### ISSUE TITLE
Feature request: contains?(range, ip)

### ISSUE THREAD

**Issue by ewildgoose** [ityonemo/net_address#3]
Hi, I really like the shape of this library. However, I came here from another library and one of my main needs is to check if an IP is within a CIDR (or a range). For example I know my local network cidr and I want to check if some IP is local to this network or not

Not a direct need, but with that feature it becomes very simple to add "is_rfc1918?(ip)" and other is_..? functions to see if the IP is a special range, eg multicast or one of the reserved ranges, etc. 

Here is a good list of is_..? functions that are simple to implement once a contains? function exists. However, I guess it would also be interesting to be able to do contains?(range, range)... hmm
  https://github.com/blackfist/iptools/blob/master/lib/iptools.ex

That said, I also ended up adding simple functions like "is_valid_ipv4(string)" for us in ecto validations, etc.

Any chance you could consider adding these functions?

**Comment by ityonemo** [comment]
Since this library implements enumerable, the contains "function" for single addresses is the built-in "in", and it takes advantage of the fast lane (it doesn't build out the list first).  I should look in to whether I can extend that to ranges.

`~i"127.0.0.1" in ~i"127.0.0.0/24"` ==> `true`

The extra functions seem reasonable!  Will accept a pr, but lmk if you don't have time for that.  Do keep in mind that I adhere strictly to the convention that is_* prefix on functions is reserved for guards; simply ? Should be sufficient to indicate that the function is boolean.

**Comment by ewildgoose** [comment]
For a range, I guess we need a function to find the first and last address in the range. Then we can apply the "in" as you show above to both ends. If they are both inside then the range is in the range. 

The "contains" function seems to be the key. Must of the other things seem to key off that.

**Comment by ityonemo** [comment]
updated as a part of 0.3.0

range and subnet `Kernel.in` is upgraded to allow ranges and subnets, and is now explicitly (instead of implicitly) documented:  https://hexdocs.pm/net_address/IP.Range.html#module-membership
https://hexdocs.pm/net_address/IP.Subnet.html#module-membership

Also provides is_in functions for use in guards:
https://hexdocs.pm/net_address/IP.Range.html#is_in/2
https://hexdocs.pm/net_address/IP.Subnet.html#is_in/2

**Comment by LrsK** [comment]
I'm using version 0.3.1 and I have come across something odd. If you want to check for membership in a subnet between IPv4 and IPv6 subnets, the following code will result in true:

```elixir
Erlang/OTP 27 [erts-15.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.18.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> subnet1 = IP.Subnet.from_string!("2001:700:4300::/40")
~i"2001:700:4300::/40"
iex(2)> ip1 = IP.Subnet.from_string!("192.168.55.4/32")
~i"192.168.55.4/32"
iex(3)> ip1 in subnet1
false                      # this seems fine
iex(4)> subnet1 in ip1
true                       # this should probably be false?
```

I would normally put a check on the subnet to see if it's an IPv4 or IPv6 address, but there doesn't seem to be any functions that provide that information. I'm new to Elixir so I may be overlooking something.
